import { library } from "@fortawesome/fontawesome-svg-core";
import { faGoogle, faFacebook, faGithub, faPaypal, faCcVisa, faCcMastercard } from "@fortawesome/free-brands-svg-icons";
import {} from "@fortawesome/free-regular-svg-icons"
import {
  faBoxes,
  faHome,
  faUpload,
  faCaretUp,
  faSearch,
  faSignOutAlt,
  faTrash,
  faUserCircle,
  faPencilAlt,
  faShoppingCart,
  faHeart,
  faShare,
  faEye,
  faArrowCircleLeft,
  faArrowLeft,
  faQuestion,
  faAngleRight,
  faThumbsUp,
  faUser,
  faHistory,
  faComment,
  faVoteYea,
  faWrench,
  faCamera,
  faEdit,
  faCartPlus,
  faPaperPlane,
  faAngleUp,
  faAngleDown,
  faCheckCircle,
  faHamburger
} from "@fortawesome/free-solid-svg-icons";

export default library.add({
  faHamburger,
  faBoxes,
  faUpload,
  faHome,
  faAngleUp,
  faAngleDown,
  faAngleRight,
  faPaperPlane,
  faCartPlus,
  faEdit,
  faCamera,
  faWrench,
  faVoteYea,
  faComment,
  faHistory,
  faUser,
  faThumbsUp,
  faQuestion,
  faCaretUp,
  faSearch,
  faCheckCircle,
  faSignOutAlt,
  faTrash,
  faUserCircle,
  faGoogle,
  faFacebook,
  faPencilAlt,
  faShoppingCart,
  faHeart,
  faShare,
  faEye,
  faArrowCircleLeft,
  faArrowLeft,
  faGithub,
  faPaypal, 
  faCcVisa, 
  faCcMastercard
});

/**
 * @typedef FileForIcons
 * @typedef এই_ফাইলটি_শুধুমাত্র_FontAwesomeIcon_এর_জন্য।
  */